export const ENG_PREMIER_LOGOS = [
  "AFC Bournemouth.png",
  "Arsenal FC.png",
  "Aston Villa.png",
  "Brentford FC.png",
  "Brighton & Hove Albion.png",
  "Chelsea FC.png",
  "Crystal Palace.png",
  "Everton FC.png",
  "Fulham FC.png",
  "Ipswich Town.png",
  "Leicester City.png",
  "Liverpool FC.png",
  "Manchester City.png",
  "Manchester United.png",
  "Newcastle United.png",
  "Nottingham Forest.png",
  "Southampton FC.png",
  "Tottenham Hotspur.png",
  "West Ham United.png",
  "Wolverhampton Wanderers.png"
];
export const FRA_LIGUE1_LOGOS = [
  "AJ Auxerre.png",
  "AS Monaco.png",
  "AS Saint-Étienne.png",
  "Angers SCO.png",
  "FC Nantes.png",
  "FC Toulouse.png",
  "LOSC Lille.png",
  "Le Havre AC.png",
  "Montpellier HSC.png",
  "OGC Nice.png",
  "Olympique Lyon.png",
  "Olympique Marseille.png",
  "Paris Saint-Germain.png",
  "RC Lens.png",
  "RC Strasbourg Alsace.png",
  "Stade Brestois 29.png",
  "Stade Reims.png",
  "Stade Rennais FC.png"
];
export const GER_BUNDESLIGA_LOGOS = [
  "1.FC Heidenheim 1846.png",
  "1.FC Union Berlin.png",
  "1.FSV Mainz 05.png",
  "Bayer 04 Leverkusen.png",
  "Bayern Munich.png",
  "Borussia Dortmund.png",
  "Borussia Mönchengladbach.png",
  "Eintracht Frankfurt.png",
  "FC Augsburg.png",
  "FC St. Pauli.png",
  "Holstein Kiel.png",
  "RB Leipzig.png",
  "SC Freiburg.png",
  "SV Werder Bremen.png",
  "TSG 1899 Hoffenheim.png",
  "VfB Stuttgart.png",
  "VfL Bochum.png",
  "VfL Wolfsburg.png"
];
export const ITA_SERIEA_LOGOS = [
  "AC Milan.png",
  "AC Monza.png",
  "ACF Fiorentina.png",
  "AS Roma.png",
  "Atalanta BC.png",
  "Bologna FC 1909.png",
  "Cagliari Calcio.png",
  "Como 1907.png",
  "FC Empoli.png",
  "Genoa CFC.png",
  "Hellas Verona.png",
  "Inter Milan.png",
  "Juventus FC.png",
  "Parma Calcio 1913.png",
  "SS Lazio.png",
  "SSC Napoli.png",
  "Torino FC.png",
  "US Lecce.png",
  "Udinese Calcio.png",
  "Venezia FC.png"
];
export const ESP_LALIGA_LOGOS = [
  "Athletic Bilbao.png",
  "Atlético de Madrid.png",
  "CA Osasuna.png",
  "CD Leganés.png",
  "Celta de Vigo.png",
  "Deportivo Alavés.png",
  "FC Barcelona.png",
  "Getafe CF.png",
  "Girona FC.png",
  "RCD Espanyol Barcelona.png",
  "RCD Mallorca.png",
  "Rayo Vallecano.png",
  "Real Betis Balompié.png",
  "Real Madrid.png",
  "Real Sociedad.png",
  "Real Valladolid CF.png",
  "Sevilla FC.png",
  "UD Las Palmas.png",
  "Valencia CF.png",
  "Villarreal CF.png"
];