export const EPL_TEAMS: Record<string, string> = {
    "Arsenal": "https://loodibee.com/wp-content/uploads/Arsenal-FC-logo-300x300.png",
    "Aston Villa": "https://loodibee.com/wp-content/uploads/Aston-Villa-FC-logo-300x300.png",
    "AFC Bournemouth": "https://loodibee.com/wp-content/uploads/AFC-Bournemouth-logo-300x300.png",
    "Brentford": "https://loodibee.com/wp-content/uploads/Brentford-FC-logo-300x300.png",
    "Brighton & Hove Albion": "https://loodibee.com/wp-content/uploads/Brighton-Hove-Albion-logo-300x300.png",
    "Chelsea": "https://loodibee.com/wp-content/uploads/Chelsea-FC-logo-300x300.png",
    "Crystal Palace": "https://loodibee.com/wp-content/uploads/Crystal-Palace-FC-logo-300x300.png",
    "Everton": "https://loodibee.com/wp-content/uploads/Everton-FC-logo-300x300.png",
    "Fulham": "https://loodibee.com/wp-content/uploads/Fulham-FC-logo-300x300.png",
    "Liverpool": "https://loodibee.com/wp-content/uploads/Liverpool-FC-logo-300x300.png",
    "Manchester City": "https://loodibee.com/wp-content/uploads/Manchester-City-FC-logo-300x300.png",
    "Manchester United": "https://loodibee.com/wp-content/uploads/Manchester-United-FC-logo-300x300.png",
    "Newcastle United": "https://loodibee.com/wp-content/uploads/Newcastle-United-logo-300x300.png",
    "Nottingham Forest": "https://loodibee.com/wp-content/uploads/Nottingham-Forest-FC-logo-300x300.png",
    "Tottenham Hotspur": "https://loodibee.com/wp-content/uploads/Tottenham-Hotspur-logo-300x300.png",
    "West Ham United": "https://loodibee.com/wp-content/uploads/West-Ham-United-FC-logo-300x300.png",
    "Wolverhampton Wanderers": "https://loodibee.com/wp-content/uploads/Wolverhampton-Wanderers-logo-300x300.png",
    "Ipswich Town": "https://loodibee.com/wp-content/uploads/Ipswich-Town-FC-logo-300x300.png",
    "Leicester City": "https://loodibee.com/wp-content/uploads/Leicester-City-FC-logo-300x300.png",
    "Southampton": "https://loodibee.com/wp-content/uploads/Southampton-FC-logo-300x300.png",
  };
  