import { TeamTypeInit } from "@/lib/Types/Team.Type";

export const EPL_TEAMS: TeamTypeInit[] = [
  {
    name: "Arsenal",
    slug: "arsenal",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Arsenal-FC-logo.png",
  },
  {
    name: "Aston Villa",
    slug: "aston-villa",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Aston-Villa-FC-logo.png",
  },
  {
    name: "Bournemouth",
    slug: "bournemouth",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/AFC-Bournemouth-logo.png",
  },
  {
    name: "Brentford",
    slug: "brentford",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Brentford-FC-logo.png",
  },
  {
    name: "Brighton",
    slug: "brighton",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Brighton-Hove-Albion-logo.png",
  },
  {
    name: "Chelsea",
    slug: "chelsea",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Chelsea-FC-logo.png",
  },
  {
    name: "Crystal Palace",
    slug: "crystal-palace",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Crystal-Palace-FC-logo.png",
  },
  {
    name: "Everton",
    slug: "everton",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Everton-FC-logo.png",
  },
  {
    name: "Fulham",
    slug: "fulham",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Fulham-FC-logo.png",
  },
  {
    name: "Ipswich Town",
    slug: "ipswich",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Ipswich-Town-FC-logo.png",
  },
  {
    name: "Leicester City",
    slug: "leicester",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Leicester-City-FC-logo.png",
  },
  {
    name: "Liverpool",
    slug: "liverpool",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Liverpool-FC-logo.png",
  },
  {
    name: "Manchester City",
    slug: "man-city",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Manchester-City-FC-logo.png",
  },
  {
    name: "Manchester Utd",
    slug: "man-united",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Manchester-United-FC-logo.png",
  },
  {
    name: "Newcastle Utd",
    slug: "newcastle",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Newcastle-United-logo.png",
  },
  {
    name: "Nott'ham Forest",
    slug: "Nott'hamForest",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Nottingham-Forest-FC-logo.png",
  },
  {
    name: "Southampton",
    slug: "southampton",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Southampton-FC-logo.png",
  },
  {
    name: "Tottenham",
    slug: "tottenham",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Tottenham-Hotspur-logo.png",
  },
  {
    name: "West Ham",
    slug: "west-ham",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/West-Ham-United-FC-logo.png",
  },
  {
    name: "Wolves",
    slug: "wolves",
    league: "ENG-Premier League",
    season: "2425",
    logo: "https://loodibee.com/wp-content/uploads/Wolverhampton-Wanderers-logo.png",
  },
];
